lenguaje: python
python:
  - "2.7"

virtualenv:
  system_sites_packages: true


install:
  - sudo mkdir -p /etc/ssl/private-copy; sudo mkdir -p /etc/ssl/private; sudo mv /etc/ssl/private/* /etc/ssl/private-copy/; sudo rm -r /etc/ssl/private; sudo mv /etc/ssl/private-copy /etc/ssl/private; sudo chmod -R 0700 /etc/ssl/private; sudo chown -R postgres /etc/ssl/private
  - sudo su -c "sudo -u postgres /usr/lib/postgresql/9.6/bin/postgres -c "config_file=/etc/postgresql/9.6/main/postgresql.conf" > /tmp/pg.log 2>&1 & sleep 5s"

  - createdb database